name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-native:
    strategy:
      fail-fast: false

      # Set up a matrix to run the following 3 configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        os: [windows-x64, linux-x64, macos-aarch64, macos-x64]
        build_type: [Release]
        include:
          - os: windows-x64
            runner: windows-latest
          - os: linux-x64
            runner: ubuntu-latest
          - os: macOS-aarch64
            runner: macos-latest
          - os: macOS-x64
            runner: macos-13

    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: >
        cmake
        -S ${{ github.workspace }}
        -B build
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: >
        cmake
        --build build
        --config ${{ matrix.build_type }}

    - name: Test
      run: >
        python tests/test_examples.py
        --build build
        --config ${{ matrix.build_type }}
